site_name: xproxy docs
site_url: https://xproxy.readthedocs.com
repo_url: https://github.com/nmhjklnm/xproxy

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  extra_css:
    - docs/extra.css
  repo_name: xproxy
  features:
    - navigation.tabs

plugins:
  - search:
      lang:
        - en
        - zh
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_bases: true
            heading_level: 3
            show_root_heading: true
            show_root_full_path: false
            allow_inspection: true
            parameter_headings: true
