name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt 
        pip install .   

    - name: Debug
      run: |
        ls -R
        python -c "import sys; print(sys.path)"
        echo "PYTHONPATH: $PYTHONPATH"

    - name: Build and Deploy
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        mkdocs gh-deploy --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
